### PR TITLE
remove smek* words

### PR DESCRIPTION
**Pull request by mlutze**

### CODE REVIEW

**Comment by SSoelvsten** [comment]
From Collins explanations of words
```
SMEKE	(Scots) to smoke, also SMEIK [v SMEKED, SMEKING, SMEKES]
SMEKED	SMEKE, (Scots) to smoke, also SMEIK [v]
SMEKES	SMEKE, (Scots) to smoke, also SMEIK [v]
SMEKING	SMEKE, (Scots) to smoke, also SMEIK [v]
```

**Comment by mlutze** [comment]
I'd argue that Scots isn't English (there's a separate [Wikipedia for Scots](https://sco.wikipedia.org/wiki/Main_Page), after all)

**Comment by SSoelvsten** [comment]
I do understand, that (especially as a non-native speaker) it seems weird to have one's game being made much harder by running into a word in Scots.

It is quite a slippery slope though. What about the following languages? Should they also be removed?

- Hawaiian
- [Hindi](https://hi.wikipedia.org/wiki/%E0%A4%AE%E0%A5%81%E0%A4%96%E0%A4%AA%E0%A5%83%E0%A4%B7%E0%A5%8D%E0%A4%A0)
- South African
- [Tagalog](https://tl.wikipedia.org/)
- Spenser and Shakespeare
- French

But, considering the political climate over on the Atlantic Archipelago, I do just want to make it very clear, that this in no way ought to be understood as taking the side of the British...

**Comment by SSoelvsten** [comment]
Superseeded by #90 .

**Pull request closed without merging**
